name: .NET

on:
  push:
    branches:
      - main
    paths:
      - 'Application/**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
        
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      
    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
